version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        
        working_directory: ~/project/
        
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-pip-deps-{{ checksum "requirements.txt" }}
                      - v1-pip-deps-

            - run:
                  name: Install python dependencies
                  command: |
                      make setup
                      source ~/.devops/bin/activate
                      make install
            - save_cache:
                  key: v1-pip-deps-{{ checksum "requirements.txt" }}
                  paths:
                      - ~/.devops

            - run:
                  name: Install hadolint
                  command: |
                      sudo make install-hadolint
            - run:
                  name: Run Lint
                  command: |
                      source ~/.devops/bin/activate
                      make lint
            - run:
                  name: Run Tests
                  command: |
                      source ~/.devops/bin/activate
                      make test-junit
            - store_test_results:
                  path: ~/test-results

            - store_artifacts:
                  path: ~/test-results

workflows:
    main:
        jobs:
            - build